version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: guild-site-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - guild-site-network

  mongo-express:
    image: mongo-express:latest
    container_name: guild-site-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - guild-site-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: guild-site-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - guild-site-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: guild-site-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - guild-site-network

volumes:
  mongodb_data:

networks:
  guild-site-network:
    driver: bridge
